In [40]:
import pandas as pd
import numpy as np

tomsk_lng = '84.969883'
tomsk_lat = '56.475882'
path = '/home/kirill/Music/dumb_df_exp_filtered.csv'

In [41]:
def make_url(lat_list, lng_list, addresses, area_list):
    count = 0
    points_str = 'pt='
    for lat,lng,address,area in zip(lat_list, lng_list, addresses, area_list):
        
        if area<5000:
            continue
        lat = round(lat,4)
        lng = round(lng,4)
        temp_point = f'~{lng},{lat}'
        if count == 0:
            temp_point = f'{lng},{lat}'
        points_str += temp_point
        count+=1
    alt_url = f'https://yandex.ru/maps/67/tomsk/?l=sat&ll={tomsk_lng},{tomsk_lat}&{points_str}&z=12&l=map'
    url = f'https://yandex.ru/maps/?ll={tomsk_lng},{tomsk_lat}&{points_str}'
    return url, alt_url

def has_numbers(inputString):
    return any(char.isdigit() for char in inputString)

def correct_df(df):
    print(df.shape)
    df = df.drop_duplicates(['lng','lat'], keep= 'last')
    # df = df.drop_duplicates(['address'], keep= 'last')
    # df = df.drop_duplicates(['organizations'], keep= 'last')
    area_list = df['real_area'].tolist()
    crop_names = df['crop_name'].tolist()
    print(df.shape)
#     for i in range(len(crop_names)):
#         if crop_names[i][:4]=='tile':
#                 area_list[i] = area_list[i]/1.65/1.65
#     df['real_area'] = area_list
    return df

def find_closest_point(lat_list,lng_list,lat_point,lng_point,list_of_names):
    
    dist_min = 100
    dist_second = 0
    cnt = 0
    cnt_min = 0
    name = ''
    for crop_name,lat,lng in zip(list_of_names, lat_list, lng_list):
        dist_temp = np.sqrt( (lat_point-lat)**2 + (lng_point-lng)**2 )
        cnt+=1
        if dist_temp < dist_min:
            cnt_min = cnt
            dist_second = dist_min
            name_second = name
            dist_min = dist_temp
            name = crop_name
    return cnt_min, dist_min,name, dist_second, name_second

# def feature()
#     df_zero_org = df[df['organizations']=='[]']
#     print(df_zero_org.shape)
#     df_filt_org = df[df['organizations']!='[]']
#     print(df_filt_org.shape)
#     df_filt_org = df.drop_duplicates(['address','organizations'], keep= 'last')
#     print(df_filt_org.shape)
#     df_new = pd.concat([df_zero_org,df_filt_org],ignore_index=True)
#     print(df_new.shape)
#     df_new.head()

In [42]:
df = pd.read_csv(path)
# print(df.head())
df = df[df['real_area']>1000]
df = correct_df(df)
df.reset_index(inplace = True)

(1978, 7)
(1517, 7)

In [43]:
# delete_list = []
# count = 0
# for index, row in df.iterrows():
#     real_list = eval(row['organizations'])
#     for x in real_list:
#         if x['type']=='Жилой комплекс':
#             count+=1
#             delete_list.append(index)
# #             print(x['name'])
# print(list(set(delete_list)))
# df.drop(df.index[list(set(delete_list))],inplace = True)
# df.reset_index(inplace = True)
# df.drop(['index','level_0'], axis = 1,inplace = True)

In [44]:
df_exp = df
df_exp.drop(['index','crop_name','object_id'],axis=1, inplace=True)
df_exp.head()

,lng,lat,real_area,address,organizations
0,56.459439,84.958160,1511.1,"Россия, Томск, улица Белинского, 86","[{'name': 'Lege Artis', 'type': 'Косметология'..."
1,56.461796,84.954998,1067.1,"Россия, Томск, улица Пирогова, 8",[{'name': 'Томский областной институт повышени...
2,56.498097,85.033193,1466.2,"Россия, Томск, улица Клюева, 26","[{'name': 'Детские игровые залы и площадки', '..."
3,56.500521,85.031723,2556.6,"Россия, Томск, улица Клюева, 24","[{'name': 'Вольт-АС', 'type': 'Электромонтажны..."
4,56.590192,84.908629,1567.5,"Россия, Томская область, Северск, Коммунистиче...","[{'name': 'Торговый центр', 'type': 'Торговый ..."

In [45]:
area_list = df['real_area'].tolist()
area_list = [round(ar,1) for ar in area_list]
df_exp['real_area'] = area_list
df_exp.head(15)

,lng,lat,real_area,address,organizations
0,56.459439,84.958160,1511.1,"Россия, Томск, улица Белинского, 86","[{'name': 'Lege Artis', 'type': 'Косметология'..."
1,56.461796,84.954998,1067.1,"Россия, Томск, улица Пирогова, 8",[{'name': 'Томский областной институт повышени...
2,56.498097,85.033193,1466.2,"Россия, Томск, улица Клюева, 26","[{'name': 'Детские игровые залы и площадки', '..."
3,56.500521,85.031723,2556.6,"Россия, Томск, улица Клюева, 24","[{'name': 'Вольт-АС', 'type': 'Электромонтажны..."
4,56.590192,84.908629,1567.5,"Россия, Томская область, Северск, Коммунистиче...","[{'name': 'Торговый центр', 'type': 'Торговый ..."
5,56.590501,84.910469,1133.5,"Россия, Томская область, Северск, Коммунистиче...","[{'name': 'Примула', 'type': 'Аптека', 'phone'..."
6,56.591379,84.909283,1749.7,"Россия, Томская область, Северск, Коммунистиче...","[{'name': 'Втемпуре', 'type': 'Суши-бар', 'pho..."
7,56.592586,84.908137,4515.2,"Россия, Томская область, Северск, Коммунистиче...","[{'name': 'Северский музыкальный театр', 'type..."
8,56.509299,84.974017,2504.6,"Россия, Томск, Ленинский район, микрорайон Каш...","[{'name': 'Квартиры на Карла Ильмера', 'type':..."
9,56.509854,84.978678,1372.8,"Россия, Томск, улица 79-й Гвардейской Дивизии, 12","[{'name': 'Абрикос', 'type': 'Супермаркет', 'p..."
10,56.510268,84.972702,1038.7,"Россия, Томск, проспект Мира, 13","[{'name': 'Изумрудный город', 'type': 'Торговы..."
11,56.510780,84.979310,1257.8,"Россия, Томск, улица 79-й Гвардейской Дивизии, 15","[{'name': 'Реактор', 'type': 'Спортивно-развле..."
12,56.510962,84.976123,2103.4,"Россия, Томск, улица 79-й Гвардейской Дивизии, 20","[{'name': 'Улица 79-й Гвардейской Дивизии', 't..."
13,56.511589,84.973963,1410.6,"Россия, Томск, улица 79-й Гвардейской Дивизии, 24","[{'name': 'Premier V', 'type': 'Магазин одежды..."
14,56.511648,84.978182,2208.9,"Россия, Томск, улица 79-й Гвардейской Дивизии, 21",[{'name': 'Томский коммунально-строительный те...

In [46]:
df_exp['Объект на карте'] = None
for iteration,row in df_exp.iterrows():
    lng = row['lat'] 
    lat = row['lng'] 
    url = f"https://yandex.ru/maps/?ll={lng},{lat}&pt={lng},{lat}&z=18&l=map"
    hyper_url = f'=HYPERLINK("{url}", "Ссылка")'
    df_exp.at[iteration,'address'] = row['address'][7:]
    df_exp.at[iteration,'Объект на карте'] = hyper_url

In [47]:
df_exp.drop(['lng','lat'],axis=1,inplace = True)
df_exp.rename(columns={'real_area': 'Площадь, м.кв.', 'address': 'Адрес'}, inplace=True)
df_exp.head(10)

,"Площадь, м.кв.",Адрес,organizations,Объект на карте
0,1511.1,"Томск, улица Белинского, 86","[{'name': 'Lege Artis', 'type': 'Косметология'...","=HYPERLINK(""https://yandex.ru/maps/?ll=84.9581..."
1,1067.1,"Томск, улица Пирогова, 8",[{'name': 'Томский областной институт повышени...,"=HYPERLINK(""https://yandex.ru/maps/?ll=84.9549..."
2,1466.2,"Томск, улица Клюева, 26","[{'name': 'Детские игровые залы и площадки', '...","=HYPERLINK(""https://yandex.ru/maps/?ll=85.0331..."
3,2556.6,"Томск, улица Клюева, 24","[{'name': 'Вольт-АС', 'type': 'Электромонтажны...","=HYPERLINK(""https://yandex.ru/maps/?ll=85.0317..."
4,1567.5,"Томская область, Северск, Коммунистический пр...","[{'name': 'Торговый центр', 'type': 'Торговый ...","=HYPERLINK(""https://yandex.ru/maps/?ll=84.9086..."
5,1133.5,"Томская область, Северск, Коммунистический пр...","[{'name': 'Примула', 'type': 'Аптека', 'phone'...","=HYPERLINK(""https://yandex.ru/maps/?ll=84.9104..."
6,1749.7,"Томская область, Северск, Коммунистический пр...","[{'name': 'Втемпуре', 'type': 'Суши-бар', 'pho...","=HYPERLINK(""https://yandex.ru/maps/?ll=84.9092..."
7,4515.2,"Томская область, Северск, Коммунистический пр...","[{'name': 'Северский музыкальный театр', 'type...","=HYPERLINK(""https://yandex.ru/maps/?ll=84.9081..."
8,2504.6,"Томск, Ленинский район, микрорайон Каштак, ми...","[{'name': 'Квартиры на Карла Ильмера', 'type':...","=HYPERLINK(""https://yandex.ru/maps/?ll=84.9740..."
9,1372.8,"Томск, улица 79-й Гвардейской Дивизии, 12","[{'name': 'Абрикос', 'type': 'Супермаркет', 'p...","=HYPERLINK(""https://yandex.ru/maps/?ll=84.9786..."

In [48]:
df_exp['organizations'][0]

"[{'name': 'Lege Artis', 'type': 'Косметология', 'phone': '+7 (3822) 20-05-80'}, {'name': 'Муза', 'type': 'Косметология', 'phone': '+7 (3822) 59-14-74'}, {'name': 'Студия Виктора Вороного', 'type': 'Салон красоты', 'phone': '+7 (983) 348-30-38'}, {'name': 'Медицинский центр Мульти Клиник на Белинского', 'type': 'Медцентр, клиника', 'phone': '+7 (3822) 90-19-41', 'url': 'http://multiclinic.ru/'}]"

In [49]:
for iteration, row in df_exp.iterrows():
    real_list = eval(row['organizations'])
#     if iteration % 10:
# #         print(iteration)
    if len(real_list)<=3:
        string = ''
        for i,x in enumerate(real_list):
#             print(x)
            string += f"{i+1}.Имя - {x['name']}"
            if 'type' in x.keys():
                string += f", тип - {x['type']}, "
            if 'phone' in x.keys():
                string += f"тел. - {x['phone']} ; "
        df_exp.at[iteration,'organizations'] = string
        
    else:
        df_exp.at[iteration,'organizations'] = 'Больше трёх организаций' 
        
df_exp.head(10)

,"Площадь, м.кв.",Адрес,organizations,Объект на карте
0,1511.1,"Томск, улица Белинского, 86",Больше трёх организаций,"=HYPERLINK(""https://yandex.ru/maps/?ll=84.9581..."
1,1067.1,"Томск, улица Пирогова, 8",Больше трёх организаций,"=HYPERLINK(""https://yandex.ru/maps/?ll=84.9549..."
2,1466.2,"Томск, улица Клюева, 26",Больше трёх организаций,"=HYPERLINK(""https://yandex.ru/maps/?ll=85.0331..."
3,2556.6,"Томск, улица Клюева, 24","1.Имя - Вольт-АС, тип - Электромонтажные работ...","=HYPERLINK(""https://yandex.ru/maps/?ll=85.0317..."
4,1567.5,"Томская область, Северск, Коммунистический пр...",Больше трёх организаций,"=HYPERLINK(""https://yandex.ru/maps/?ll=84.9086..."
5,1133.5,"Томская область, Северск, Коммунистический пр...","1.Имя - Примула, тип - Аптека, тел. - +7 (3823...","=HYPERLINK(""https://yandex.ru/maps/?ll=84.9104..."
6,1749.7,"Томская область, Северск, Коммунистический пр...",Больше трёх организаций,"=HYPERLINK(""https://yandex.ru/maps/?ll=84.9092..."
7,4515.2,"Томская область, Северск, Коммунистический пр...",Больше трёх организаций,"=HYPERLINK(""https://yandex.ru/maps/?ll=84.9081..."
8,2504.6,"Томск, Ленинский район, микрорайон Каштак, ми...","1.Имя - Квартиры на Карла Ильмера, тип - Жильё...","=HYPERLINK(""https://yandex.ru/maps/?ll=84.9740..."
9,1372.8,"Томск, улица 79-й Гвардейской Дивизии, 12",Больше трёх организаций,"=HYPERLINK(""https://yandex.ru/maps/?ll=84.9786..."

In [50]:
df_exp.rename(columns={'organizations': 'Организации'}, inplace=True)

In [26]:
from pandas import ExcelWriter

writer = ExcelWriter('PythonExport.xlsx')
df_exp.to_excel(writer,'Sheet5')
writer.save()

In [171]:
lng_list = df['lat'].tolist()
lat_list = df['lng'].tolist()
area_list = df['real_area'].tolist()
addresses = df['address'].tolist()
url,alt_url = make_url(lat_list, lng_list, addresses, area_list)
print(url)

https://yandex.ru/maps/?ll=84.969883,56.475882&pt=84.9592,56.4787~85.0339,56.6253~84.8123,56.6189~85.0147,56.5011~85.0077,56.6191~85.0151,56.4702~85.0244,56.6187~85.0413,56.6231~84.9744,56.5019~84.9832,56.4683~84.8978,56.6036~85.0233,56.504~84.8115,56.6177~84.8114,56.6201~84.9676,56.4531~84.8114,56.6213~84.8092,56.6225~84.9968,56.6149~84.9971,56.472~84.947,56.5141~85.0111,56.6221~84.9954,56.6239~85.0147,56.5011~85.0016,56.6179~85.0944,56.5153~84.9986,56.615~85.0038,56.6155~85.0119,56.6087~84.991,56.47~84.9637,56.4632

In [59]:
lng_point = 84.842877
lat_point = 56.608231
list_of_names = df['crop_name'].tolist()
cnt_min, dist_min, name ,d_sec,name_sec= find_closest_point(lat_list,lng_list,lat_point,lng_point,list_of_names)
print(cnt_min)
print(dist_min)
print(name)
print(d_sec)
print(name_sec)

271
0.0013632902738306264
big_18_41
0.002066370953269607
big_18_40

In [10]:

output_path = 'outputs/masks_viz/'

df = pd.read_csv('outputs/masks_viz/dumb_df_exp_filtered.csv')
df = correct_df(df)

print(df[df['crop_name']=='big_15_31'].shape)
# df.to_csv(output_path + 'dumb_df_exp_filtered.csv', index=False)

lat_list = df['lng'].tolist()
lng_list = df['lat'].tolist()
addresses = df['address'].tolist()
area_list = df['real_area'].tolist()
list_of_names = df['crop_name'].tolist()
url = make_url(lat_list, lng_list, addresses, area_list)
print(url)

# 85.023749%2C56.504062
lat_point = 56.504062
lng_point = 85.023749
cnt_min, dist_min, name ,d_sec,name_sec= find_closest_point(lat_list,lng_list,lat_point,lng_point,list_of_names)
print(cnt_min)
print(dist_min)
print(name)
print(d_sec)
print(name_sec)

SyntaxError: invalid character in identifier (<ipython-input-10-afe528d08224>, line 16)